INSERT INTO ArtistT VALUES
('Dewain', 'Ellsom', 'Ocular Disease', 84.58, 16, 'Thailand', 'Prakhon Chai', 'Suite 98'),
('Denver', 'Vayne', 'Furnishings', 32.46, 5, 'Cuba', 'Guane', 'Suite 6'),
('Lane', 'Wilsone', 'KnockoutJS', 0.61, 5, 'China', 'Shuitianzhuang', '2nd Floor'),
('Feodora', 'Whapple', 'Urban Infill', 36.45, 2, 'China', 'Sishilichengzi', 'Suite 86'),
('Sherwin', 'Gainsford', 'DBC', 63.22, 12, 'United States', 'Phoenix', '3rd Floor'),
('Fredi', 'Kramer', 'PXE', 35.97, 25, 'Philippines', 'Malaruhatan', 'Suite 99'),
('Pooh', 'Cannaway', 'Continuous Improvement', 78.1, 9, 'Nigeria', 'Wuyo', 'Room 892'),
('Florrie', 'Mendes', 'RSLinx', 15.09, 16, 'China', 'Jiaotang', 'PO Box 68052'),
('Ami', 'Varcoe', 'TCM', 39.31, 16, 'Nepal', 'Bīrganj', 'Suite 44'),
('Dorella', 'Otridge', 'HP', 32.56, 11, 'France', 'Bastia', 'Suite 35'),
('Cece', 'Desforges', 'Urban Geography', 62.66, 10, 'Sweden', 'Värnamo', 'Suite 46'),
('Kanya', 'McMaster', 'DMZ', 25.5, 9, 'Vietnam', 'Tân Hiệp', 'Apt 763'),
('Prescott', 'Posnette', 'Erlang', 12.63, 20, 'Indonesia', 'Pajeksan', 'Suite 18'),
('Hagan', 'Snozzwell', 'Emergency Room', 36.86, 27, 'Sweden', 'Umeå', 'PO Box 21128'),
('Cleavland', 'Methven', 'ATG CSC', 8.14, 20, 'Indonesia', 'Bulu', 'Suite 81'),
('Edmon', 'Kennelly', 'PPTP', 87.39, 5, 'Portugal', 'Souto de Cima', 'PO Box 52219'),
('Pietra', 'Ife', 'Government Procurement', 26.1, 4, 'Russia', 'Obninsk', '3rd Floor'),
('Conchita', 'Conneau', 'Nastran', 89.35, 7, 'Uzbekistan', 'Qozonketkan', '11th Floor'),
('Vin', 'Bebb', 'Broadcast Journalism', 15.35, 6, 'China', 'Huangshagang', 'PO Box 6938'),
('Alvinia', 'O\'Tierney', 'ASME', 76.28, 28, 'Iran', 'Arāk', 'Room 391');